version: '3'
services:
  api:
    container_name: cookie_test_api
    environment: 
      - PGUSER=cookie_monster
      - PGHOST=db
      - PGPASSWORD=cookiepass
      - PGDATABASE=cookie_quiz_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: cookie_test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=cookie_quiz_test
      - POSTGRES_PASSWORD=cookiepass
volumes:
  test_db:
networks: 
  default:
    name: cookie_test
